name: Telegram Video Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Test FFmpeg installation
      run: ffmpeg -version
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v || echo "No tests found, skipping..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bot (webhook mode)
      if: ${{ secrets.BOT_TOKEN != '' && secrets.WEBHOOK_URL != '' }}
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        PORT: 8080
      run: |
        timeout 300 python -m src.bot || echo "Bot ran for 5 minutes in demo mode"
